import { createFileRoute } from "@tanstack/react-router";
import { useCallback, useMemo, useState } from "react";
import { ClientOnly } from "@/components/ClientOnly";
import { mockDataset } from "@/data/mock";
import type { Entity } from "@/domain/entities";
import { useLiveEntities } from "@/hooks/useLiveEntities";
import { useInsightFeed } from "@/hooks/useInsightFeed";
import { useConsoleFlags } from "@/hooks/useConsoleFlags";
import { usePanelVisibility } from "@/hooks/usePanelVisibility";
import { useConsoleDataset } from "@/hooks/useConsoleDataset";
import { useSelectedTrack } from "@/hooks/useSelectedTrack";
import { lodForHeight } from "@/lib/geo/spatial";
import { generateStressDataset } from "@/lib/dev/synthetic";
import { SNAPSHOT_LIMITS } from "@/domain/constants";
import {
  TopBar,
  CounterStrip,
  ControlPanel,
  FiltersPanel,
  EntityPanel,
  TimelineFeed,
  AlertsPanel,
  AiInsights,
  MapCanvasDynamic,
  PanelToggles,
  ConsoleLoading,
  ConsoleFooter,
} from "@/components/console";
import type { CameraFocus, GlobeViewState } from "@/components/console";
import type {
  ActiveAlert,
  AiInsight,
  DataMode,
  Filters,
  LayerVisibility,
  SelectedEntity,
} from "@/domain/console";

export const Route = createFileRoute("/")({
  head: () => ({
    meta: [
      { title: "OmniSky — Global Air, Sea & Space Intelligence" },
      {
        name: "description",
        content:
          "Live intelligence console tracking aircraft, vessels, satellites, and rocket launches across the globe.",
      },
      { property: "og:title", content: "OmniSky — Global Air, Sea & Space Intelligence" },
      {
        property: "og:description",
        content:
          "Live intelligence console tracking aircraft, vessels, satellites, and rocket launches across the globe.",
      },
      { property: "og:type", content: "website" },
      { name: "twitter:card", content: "summary_large_image" },
    ],
  }),
  component: Index,
});

function Index() {
  const { settings, updateSettings } = useConsoleSettings();
  const [layers, setLayers] = useState<LayerVisibility>(settings.defaultLayers);
  const [filters, setFilters] = useState<Filters>({
    search: "",
    riskRange: [0, 100],
    affiliations: [],
    classifications: [],
  });
  const [selected, setSelected] = useState<SelectedEntity>(null);
  const [mode, setMode] = useState<DataMode>("live");
  const [view, setView] = useState<GlobeViewState>({ bounds: null, heightM: 24_000_000 });
  const [focus, setFocus] = useState<CameraFocus | null>(null);

  const { panels, togglePanel } = usePanelVisibility(settings.defaultPanels);
  const flags = useConsoleFlags();

  // Ask the backend only for what the current camera can see, with a density
  // budget derived from the zoom level.
  const viewport = useMemo(
    () => ({
      bounds: view.bounds,
      limit: Math.min(SNAPSHOT_LIMITS.maxRows, lodForHeight(view.heightM).maxIndividual * 3),
    }),
    [view],
  );

  const live = useLiveEntities(mode === "live" && !flags.stress, viewport, settings.refreshIntervalMs);

  // Alerts + AI insights are generated by a scheduled backend job in live mode.
  const generated = useInsightFeed(mode === "live");
  const alerts = mode === "live" ? generated.alerts : mockDataset.alerts;
  const insights = mode === "live" ? generated.insights : mockDataset.insights;

  const stressEntities = useMemo<Entity[]>(
    () =>
      flags.stress
        ? generateStressDataset({
            aircraft: flags.counts[0],
            ships: flags.counts[1],
            satellites: flags.counts[2],
          })
        : [],
    [flags],
  );

  const allEntities = useMemo<Entity[]>(() => {
    if (flags.stress) return [...stressEntities, ...mockDataset.launches];
    if (mode === "live") return live.entities;
    return [
      ...mockDataset.aircraft,
      ...mockDataset.ships,
      ...mockDataset.satellites,
      ...mockDataset.launches,
    ];
  }, [mode, live.entities, flags.stress, stressEntities]);

  const { filteredEntities, counts, facets } = useConsoleDataset(
    allEntities,
    layers,
    filters,
    alerts.length,
  );

  const track = useSelectedTrack(selected?.entity, mode === "live" && !flags.stress);

  const handleSelectEntity = useCallback((entity: Entity) => {
    setSelected({ entity, source: "map" });
  }, []);

  const handleSelectById = useCallback(
    (id: string) => {
      const entity = allEntities.find((e) => e.id === id);
      if (entity) setSelected({ entity, source: "list" });
    },
    [allEntities],
  );

  /** Alerts and insights carry the place they fired: fly the camera there. */
  const handleLocate = useCallback(
    (item: ActiveAlert | AiInsight) => {
      if ("entityId" in item && item.entityId) handleSelectById(item.entityId);
      if (item.location) {
        setFocus({ lat: item.location.lat, lon: item.location.lon, nonce: Date.now() });
      }
    },
    [handleSelectById],
  );

  const handleSearch = useCallback((value: string) => {
    setFilters((prev) => ({ ...prev, search: value }));
  }, []);

  const toggleLayer = useCallback((key: keyof LayerVisibility) => {
    setLayers((prev) => ({ ...prev, [key]: !prev[key] }));
  }, []);

  const handleRefresh = useCallback(() => {
    if (mode === "live") live.refresh();
    else window.location.reload();
  }, [mode, live]);

  return (
    <ClientOnly fallback={<ConsoleLoading />}>
      <div className="flex flex-col h-screen w-screen overflow-hidden bg-console-bg text-console-text">
        <TopBar
          onSearch={handleSearch}
          mode={mode}
          onModeChange={setMode}
          feedStatus={live.status}
          lastUpdated={live.lastUpdated}
          settings={settings}
          onSettingsChange={updateSettings}
        />
        <div className="flex items-center border-b border-console-border bg-console-bg">
          <div className="flex-1 min-w-0">
            <CounterStrip counts={counts} />
          </div>
          <PanelToggles panels={panels} onToggle={togglePanel} />
        </div>

        <div className="flex flex-1 min-h-0 relative">
          <ControlPanel layers={layers} onToggleLayer={toggleLayer} onRefresh={handleRefresh} />

          {panels.filters && (
            <div className="hidden lg:flex shrink-0">
              <FiltersPanel
                filters={filters}
                onChange={setFilters}
                affiliationOptions={facets.affiliations}
                classificationOptions={facets.classifications}
              />
            </div>
          )}

          <div className="flex-1 min-w-[360px] relative">
            <MapCanvasDynamic
              entities={filteredEntities}
              layers={layers}
              selectedId={selected?.entity.id ?? null}
              onSelect={handleSelectEntity}
              onViewChange={setView}
              track={track}
              focus={focus}
              showStats={flags.stats}
              dataLoading={mode === "live" && live.fetching}
            />
          </div>

          {panels.details && (
            /* On wide screens the details dock beside the globe; on smaller
               screens it slides over the map so a click always shows details. */
            <div
              className={`${
                selected ? "flex absolute right-0 top-0 bottom-0 z-30 shadow-2xl" : "hidden"
              } 2xl:static 2xl:flex 2xl:shadow-none shrink-0`}
            >
              <EntityPanel
                selected={selected}
                onClose={() => setSelected(null)}
                onSelectNearby={handleSelectEntity}
                entities={allEntities}
              />
            </div>
          )}

          {panels.alerts && (
            <div className="hidden xl:flex w-72 shrink-0 flex-col border-l border-console-border">
              <div className="flex-1 min-h-0">
                <AlertsPanel alerts={alerts} onSelect={handleLocate} />
              </div>
              <div className="flex-1 min-h-0 border-t border-console-border">
                <AiInsights insights={insights} onSelect={handleLocate} />
              </div>
            </div>
          )}

          {panels.feed && (
            <div className="hidden xl:block w-80 shrink-0">
              <TimelineFeed
                events={mode === "live" ? live.events : mockDataset.events}
                onSelect={handleSelectById}
              />
            </div>
          )}
        </div>

        <ConsoleFooter mode={mode} />
      </div>
    </ClientOnly>
  );
}

