/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApiPublicIngestAircraftRouteImport } from './routes/api/public/ingest/aircraft'
import { Route as ApiPublicIngestLaunchesRouteImport } from './routes/api/public/ingest/launches'
import { Route as ApiPublicIngestSatellitesRouteImport } from './routes/api/public/ingest/satellites'
import { Route as ApiPublicIngestVesselsRouteImport } from './routes/api/public/ingest/vessels'
import { Route as ApiPublicInsightsRunRouteImport } from './routes/api/public/insights/run'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIngestAircraftRoute = ApiPublicIngestAircraftRouteImport.update({
  id: '/api/public/ingest/aircraft',
  path: '/api/public/ingest/aircraft',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIngestLaunchesRoute = ApiPublicIngestLaunchesRouteImport.update({
  id: '/api/public/ingest/launches',
  path: '/api/public/ingest/launches',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIngestSatellitesRoute =
  ApiPublicIngestSatellitesRouteImport.update({
    id: '/api/public/ingest/satellites',
    path: '/api/public/ingest/satellites',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicIngestVesselsRoute = ApiPublicIngestVesselsRouteImport.update({
  id: '/api/public/ingest/vessels',
  path: '/api/public/ingest/vessels',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicInsightsRunRoute = ApiPublicInsightsRunRouteImport.update({
  id: '/api/public/insights/run',
  path: '/api/public/insights/run',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/api/public/ingest/aircraft': typeof ApiPublicIngestAircraftRoute
  '/api/public/ingest/launches': typeof ApiPublicIngestLaunchesRoute
  '/api/public/ingest/satellites': typeof ApiPublicIngestSatellitesRoute
  '/api/public/ingest/vessels': typeof ApiPublicIngestVesselsRoute
  '/api/public/insights/run': typeof ApiPublicInsightsRunRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/api/public/ingest/aircraft': typeof ApiPublicIngestAircraftRoute
  '/api/public/ingest/launches': typeof ApiPublicIngestLaunchesRoute
  '/api/public/ingest/satellites': typeof ApiPublicIngestSatellitesRoute
  '/api/public/ingest/vessels': typeof ApiPublicIngestVesselsRoute
  '/api/public/insights/run': typeof ApiPublicInsightsRunRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/api/public/ingest/aircraft': typeof ApiPublicIngestAircraftRoute
  '/api/public/ingest/launches': typeof ApiPublicIngestLaunchesRoute
  '/api/public/ingest/satellites': typeof ApiPublicIngestSatellitesRoute
  '/api/public/ingest/vessels': typeof ApiPublicIngestVesselsRoute
  '/api/public/insights/run': typeof ApiPublicInsightsRunRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/auth'
    | '/api/public/ingest/aircraft'
    | '/api/public/ingest/launches'
    | '/api/public/ingest/satellites'
    | '/api/public/ingest/vessels'
    | '/api/public/insights/run'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/auth'
    | '/api/public/ingest/aircraft'
    | '/api/public/ingest/launches'
    | '/api/public/ingest/satellites'
    | '/api/public/ingest/vessels'
    | '/api/public/insights/run'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/auth'
    | '/api/public/ingest/aircraft'
    | '/api/public/ingest/launches'
    | '/api/public/ingest/satellites'
    | '/api/public/ingest/vessels'
    | '/api/public/insights/run'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AuthRoute: typeof AuthRoute
  ApiPublicIngestAircraftRoute: typeof ApiPublicIngestAircraftRoute
  ApiPublicIngestLaunchesRoute: typeof ApiPublicIngestLaunchesRoute
  ApiPublicIngestSatellitesRoute: typeof ApiPublicIngestSatellitesRoute
  ApiPublicIngestVesselsRoute: typeof ApiPublicIngestVesselsRoute
  ApiPublicInsightsRunRoute: typeof ApiPublicInsightsRunRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest/aircraft': {
      id: '/api/public/ingest/aircraft'
      path: '/api/public/ingest/aircraft'
      fullPath: '/api/public/ingest/aircraft'
      preLoaderRoute: typeof ApiPublicIngestAircraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest/launches': {
      id: '/api/public/ingest/launches'
      path: '/api/public/ingest/launches'
      fullPath: '/api/public/ingest/launches'
      preLoaderRoute: typeof ApiPublicIngestLaunchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest/satellites': {
      id: '/api/public/ingest/satellites'
      path: '/api/public/ingest/satellites'
      fullPath: '/api/public/ingest/satellites'
      preLoaderRoute: typeof ApiPublicIngestSatellitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest/vessels': {
      id: '/api/public/ingest/vessels'
      path: '/api/public/ingest/vessels'
      fullPath: '/api/public/ingest/vessels'
      preLoaderRoute: typeof ApiPublicIngestVesselsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/insights/run': {
      id: '/api/public/insights/run'
      path: '/api/public/insights/run'
      fullPath: '/api/public/insights/run'
      preLoaderRoute: typeof ApiPublicInsightsRunRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AuthRoute: AuthRoute,
  ApiPublicIngestAircraftRoute: ApiPublicIngestAircraftRoute,
  ApiPublicIngestLaunchesRoute: ApiPublicIngestLaunchesRoute,
  ApiPublicIngestSatellitesRoute: ApiPublicIngestSatellitesRoute,
  ApiPublicIngestVesselsRoute: ApiPublicIngestVesselsRoute,
  ApiPublicInsightsRunRoute: ApiPublicInsightsRunRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
